### PR TITLE
Insert values from keyboard

### PR DESCRIPTION
**Pull request by zanottipaolo**
Hi!
I have added the possibility to insert values from keyboard.

_Hacktoberfest Pull Request_

### CODE REVIEW

**Comment by nishantschavan** [comment]
I wanted to try to fix this issue. Can you please assign it to me?

**Comment by zanottipaolo** [comment]
> I wanted to try to fix this issue. Can you please assign it to me?

@nishantschavan Which issue?

**Comment by nishantschavan** [comment]
Inserting inputs from keyboard.

**Comment by zanottipaolo** [comment]
> Inserting inputs from keyboard.

@nishantschavan Okay, got it. 
I have already did it. It's a pull request, not an issue.

**Comment by Bishal976** [comment]
Great job @zanottipaolo !

**Pull request merged**
